# Select programming language
language: node_js

# Select the programming language versions
node_js:
  - "stable"
  - "10"

# Configure folders with cache
cache:
  directories:
    - node_modules

# Configure notifications (email)
notifications:
  email:
    on_failure: always
    on_success: never
    recipients:
      - daniel.valenzuela@softcrum.com

# Configure pre-execution instructions
before_script:
  - npm i -g typescript
  - npm i -g yarn

# Install dependencies
install:
  - yarn install

# Execution scripts (linters, testing)
script:
  - yarn lint
  - yarn test
